package com.example.why1.retropit

import com.google.gson.annotations.SerializedName

data class DmonitorResponse(
    @SerializedName("highestCategory") val highestCategory: String,
    @SerializedName("highestCategoryPercent") val highestCategoryPercent: Int,
    @SerializedName("lowestCategory") val lowestCategory: String,
    @SerializedName("lowestCategoryPercent") val lowestCategoryPercent: Int,
    @SerializedName("entertainmentCategoryChangePercent") val entertainmentCategoryChangePercent: Int,
    @SerializedName("entertainmentCategoryChangeBudget") val entertainmentCategoryChangeBudget: Int,
    @SerializedName("entertainmentCategoryChangeUsePercent") val entertainmentCategoryChangeUsePercent: Int,
    @SerializedName("cultureCategoryChangePercent") val cultureCategoryChangePercent: Int,
    @SerializedName("cultureCategoryChangeBudget") val cultureCategoryChangeBudget: Int,
    @SerializedName("cultureCategoryChangeUsePercent") val cultureCategoryChangeUsePercent: Int,
    @SerializedName("cafeCategoryChangePercent") val cafeCategoryChangePercent: Int,
    @SerializedName("cafeCategoryChangeBudget") val cafeCategoryChangeBudget: Int,
    @SerializedName("cafeCategoryChangeUsePercent") val cafeCategoryChangeUsePercent: Int,
    @SerializedName("sportsCategoryChangePercent") val sportsCategoryChangePercent: Int,
    @SerializedName("sportsCategoryChangeBudget") val sportsCategoryChangeBudget: Int,
    @SerializedName("sportsCategoryChangeUsePercent") val sportsCategoryChangeUsePercent: Int,
    @SerializedName("foodCategoryChangePercent") val foodCategoryChangePercent: Int,
    @SerializedName("foodCategoryChangeBudget") val foodCategoryChangeBudget: Int,
    @SerializedName("foodCategoryChangeUsePercent") val foodCategoryChangeUsePercent: Int,
    @SerializedName("accommodationCategoryChangePercent") val accommodationCategoryChangePercent: Int,
    @SerializedName("accommodationCategoryChangeBudget") val accommodationCategoryChangeBudget: Int,
    @SerializedName("accommodationCategoryChangeUsePercent") val accommodationCategoryChangeUsePercent: Int,
    @SerializedName("retailCategoryChangePercent") val retailCategoryChangePercent: Int,
    @SerializedName("retailCategoryChangeBudget") val retailCategoryChangeBudget: Int,
    @SerializedName("retailCategoryChangeUsePercent") val retailCategoryChangeUsePercent: Int,
    @SerializedName("shoppingCategoryChangePercent") val shoppingCategoryChangePercent: Int,
    @SerializedName("shoppingCategoryChangeBudget") val shoppingCategoryChangeBudget: Int,
    @SerializedName("shoppingCategoryChangeUsePercent") val shoppingCategoryChangeUsePercent: Int,
    @SerializedName("transferCategoryChangePercent") val transferCategoryChangePercent: Int,
    @SerializedName("transferCategoryChangeBudget") val transferCategoryChangeBudget: Int,
    @SerializedName("transferCategoryChangeUsePercent") val transferCategoryChangeUsePercent: Int,
    @SerializedName("transportationCategoryChangePercent") val transportationCategoryChangePercent: Int,
    @SerializedName("transportationCategoryChangeBudget") val transportationCategoryChangeBudget: Int,
    @SerializedName("transportationCategoryChangeUsePercent") val transportationCategoryChangeUsePercent: Int,
    @SerializedName("medicalCategoryChangePercent") val medicalCategoryChangePercent: Int,
    @SerializedName("medicalCategoryChangeBudget") val medicalCategoryChangeBudget: Int,
    @SerializedName("medicalCategoryChangeUsePercent") val medicalCategoryChangeUsePercent: Int,
    @SerializedName("insuranceCategoryChangePercent") val insuranceCategoryChangePercent: Int,
    @SerializedName("insuranceCategoryChangeBudget") val insuranceCategoryChangeBudget: Int,
    @SerializedName("insuranceCategoryChangeUsePercent") val insuranceCategoryChangeUsePercent: Int,
    @SerializedName("subCategoryChangePercent") val subCategoryChangePercent: Int,
    @SerializedName("subCategoryChangeBudget") val subCategoryChangeBudget: Int,
    @SerializedName("subCategoryChangeUsePercent") val subCategoryChangeUsePercent: Int,
    @SerializedName("eduCategoryChangePercent") val eduCategoryChangePercent: Int,
    @SerializedName("eduCategoryChangeBudget") val eduCategoryChangeBudget: Int,
    @SerializedName("eduCategoryChangeUsePercent") val eduCategoryChangeUsePercent: Int,
    @SerializedName("mobileCategoryChangePercent") val mobileCategoryChangePercent: Int,
    @SerializedName("mobileCategoryChangeBudget") val mobileCategoryChangeBudget: Int,
    @SerializedName("mobileCategoryChangeUsePercent") val mobileCategoryChangeUsePercent: Int,
    @SerializedName("othersCategoryChangePercent") val othersCategoryChangePercent: Int,
    @SerializedName("othersCategoryChangeBudget") val othersCategoryChangeBudget: Int,
    @SerializedName("othersCategoryChangeUsePercent") val othersCategoryChangeUsePercent: Int,

)
